version: '2'
services:
  web:
    build: web
    volumes:
      - ./web:/var/www/app
    ports:
      - "3000:3000"
    links:
      - db
    env_file:
      - ./env/.env

  api:
    build: api
    volumes:
      - ./api:/var/www/app
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    ports:
      - "3000:3000"
    links:
      - db
    env_file:
      - ./env/.env

  crawler_sn:
    build: crawler_socialnetwork
    volumes:
      - ./crawler_socialnetwork:/var/app
    command: bundle exec bin/crawler
    links:
      - db
    env_file:
      - ./env/.env

  crawler_web:
    build: crawler_web
    volumes:
      - ./crawler_web:/var/app
    links:
      - db
    env_file:
      - ./env/.env

  crawler_parser:
    build: crawler_parser
    volumes:
      - ./crawler_parser:/var/app
    command: bundle exec bin/crawler
    links:
      - db
    env_file:
      - ./env/.env

  missions:
    build: missions
    volumes:
      - ./crawler:/var/app
    links:
      - db
    env_file:
      - ./env/.env

  db:
    image: postgres
    volumes:
      - ./db/data:/var/lib/postgresql/data
    env_file:
      - ./env/.env

  cache:
    image: memcached
    volumes:
      - ./db/data:/var/lib/memcached/data
    env_file:
      - ./env/.env

