version: '2'
services:

  remix:
    build: remix
    volumes:
      - ./remix:/var/www/app
    command: bundle exec rails s -b 0.0.0.0 -P/dev/null
    ports:
      - "8081:3000"
    links:
      - db
    env_file:
      - ./env/.env

  # admin_web:
  #   image: nginx:latest
  #   volumes:
  #     - ./admin_web/dist:/usr/share/nginx/html
  #     - ./admin_web/nginx:/etc/nginx/conf.d
  #   ports:
  #     - "8082:8080"

  web-register:
    image: nginx:latest
    volumes:
      - ./web-register/dist:/usr/share/nginx/html
      - ./web-register/nginx:/etc/nginx/conf.d
    ports:
      - "8083:8080"

  # admin:
  #   build: admin
  #   volumes:
  #     - ./admin:/var/www/app
  #   command: bundle exec rails s -p 3001 -b 0.0.0.0 -P/dev/null
  #   ports:
  #     - "3001:3001"
  #   links:
  #     - db
  #   env_file:
  #     - ./env/.env

  api:
    build: api
    volumes:
      - ./api:/var/www/app
    command: sh -c "QUEUE=* rake environment resque:work & bundle exec rails s -p 3000 -b 0.0.0.0 -P/dev/null"
    ports:
      - "3000:3000"
    links:
      - db
      - redis
      - cache
    env_file:
      - ./env/.env

  crawler_sn:
    extends:
      file: crawlers/docker-compose-base.yml
      service: crawler-base
    volumes:
      - ./crawlers:/var/app
      - /bundler
    command: bundle exec bin/crawler
    links:
      - db
    env_file:
      - ./env/.env

  crawler_parser:
    extends:
      file: crawlers/docker-compose-base.yml
      service: crawler-base
    volumes:
      - ./crawlers:/var/app
      - /bundler
    command: bundle exec bin/parser
    links:
      - db
      - api
    env_file:
      - ./env/.env

  # missions:
  #   build: missions
  #   volumes:
  #     - ./crawler:/var/app
  #   links:
  #     - db
  #   env_file:
  #     - ./env/.env

  db:
    image: postgres
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./env/.env

  cache:
    image: memcached
    volumes:
      - ./db/data:/var/lib/memcached/data
    env_file:
      - ./env/.env

  redis:
    image: redis
    volumes:
      - ./db/data:/var/lib/redis/data
    env_file:
      - ./env/.env
