version: '2'
services:

  api:
    build: api
    volumes:
      - ./api:/app
    ports:
      - "3000:3000"
    links:
      - db
      - redis
      - cache
    env_file:
      - .env

  resque:
    build: api
    command: rake environment resque:work
    volumes:
      - ./api:/app
    links:
      - db
      - redis
      - cache
    env_file:
      .env

  crawler:
    build: crawlers
    command: bundle exec bin/crawler
    links:
      - db
    volumes:
      - ./crawlers:/app
      - /bundler
    env_file:
      - .env

  parser:
    build: crawlers
    command: bundle exec bin/parser
    links:
      - db
      - api
    depends_on:
      - api
    volumes:
      - ./crawlers:/app
      - /bundler
    env_file:
      - .env

  db:
    image: postgres:9.6-alpine
    volumes:
      - ./db/data:/var/lib/postgresql/data

  cache:
    image: memcached:alpine

  redis:
    image: redis:alpine
