source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.0', '>= 5.0.0.1'

# Use postgresql as the database for Active Record
gem 'pg', '~> 0.18'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'

# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'

# Forms made easy for Rails! It's tied to a simple DSL, with no opinion on markup
gem 'simple_form'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'

# FriendlyId is the “Swiss Army bulldozer” of slugging and permalink plugins for ActiveRecord
gem 'friendly_id', github: 'norman/friendly_id'

# Ruby bindings for ImageMagick
gem 'rmagick'

# Classier solution for file uploads for Rails, Sinatra and other Ruby web frameworks
gem 'carrierwave', github: 'carrierwaveuploader/carrierwave'

# Module for the 'fog' gem to support Amazon Web Services
gem 'fog-aws'

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors'

# Resque is a Redis-backed Ruby library for creating background jobs, placing them on multiple queues, and processing them later.
gem 'resque'

# Flexible authentication solution for Rails with Warden.
gem 'devise'

# Token based authentication for Rails JSON APIs.
gem 'simple_token_authentication', '~> 1.0'

# OmniAuth is a flexible authentication system utilizing Rack middleware
gem 'omniauth'

# Facebook OAuth2 Strategy for OmniAuth
gem 'omniauth-facebook'

# Instagram OAuth2 Strategy for OmniAuth
gem 'omniauth-instagram'

# OmniAuth strategy for Twitter
gem 'omniauth-twitter', github: 'nextglass/omniauth-twitter'

# A Scope & Engine based, clean, powerful, customizable and sophisticated paginator for Ruby webapps
gem 'kaminari'

# Rails Action Mailer adapter for Mailgun
gem 'mailgun_rails'

# A recommendation engine using Likes and Dislikes for your Ruby/Redis application.
gem 'recommendable'

# Adds a custom CSV renderer to Rails applications
gem 'render_csv', '~> 2.0'

# Use Puma as the app server
gem 'puma', '~> 3.0'

source 'https://rails-assets.org' do
  gem 'rails-assets-jquery'
  gem 'rails-assets-jquery-ujs'
  gem 'rails-assets-bootstrap'
  gem 'rails-assets-masonry'
end

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri

  # Minitest provides a complete suite of testing facilities supporting TDD, BDD, mocking, and benchmarking.
  gem 'minitest-rails'

  # Brings back `assigns` and `assert_template` to your Rails tests
  gem 'rails-controller-testing'
end

group :development do
  gem 'listen', '~> 3.0.5'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'

  # Meta package that requires several pry extensions.
  gem 'pry-meta'

  gem 'annotate'
end

group :production do
  # Embed the V8 Javascript Interpreter into Ruby
  gem 'therubyracer'
end
